Base implementation of driver service
cooperative0zero/driver-service pull request #1
Opened 2024-09-23 08:19 UTC by cooperative0zero

Three layers are implemented: a database access layer, a business logic layer (services) and a controller layer.
Spring Data JPA was used to organize work with the database, and Liquibase was used to manage migrations. 
Driver entity consists of the name, email, phone, gender, and the car that is linked to him.
Car entity consists of the color, make, number. 
Endpoints have been developed for creating new drivers, cars, changing them, and transferring them to the soft delete status.

2024-09-23 17:45 UTC, psidarovich requested changes

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/controller/CarController.kt
> +@RequiredArgsConstructor
No more need in this annotation - you already have constuctor in 19 line

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/controller/CarController.kt
> +        return ResponseEntity<CarResponse>(response, HttpStatus.OK)
Minor: you can also use ResponseStatus annotation instead of using status in ResponseEntity

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/controller/DriverController.kt
> +        return ResponseEntity("Deleted successfully", HttpStatus.OK)
Minor: It's better to return empty body with 203 (NoContent) status

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/dto/CarRequest.kt
> +)
Minor: not a good solution, but yes, if you make fields not nullable, you get more validations

Question: can you manage the validation with not null fields?

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/dto/CarResponse.kt
> +    val isDeleted: Boolean?
Major: Response body fields should not be null

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/exceptionhandler/ExceptionHandler.kt
> +        return baseCustomException;
Check expression functions

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/mapper/CarRequestToCar.kt
> +            source.isDeleted!!
Using not null assert operator is a bad practice

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/mapper/DriverRequestToDriver.kt
> +        car.id = source.carId
Minor: check .copy() function

2024-09-23 17:45 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/mapper/DriverRequestToDriver.kt
> +            source.isDeleted!!
Minor: also it's better to use named parameters in constructor invocations with several params with same type (string for instance)

2024-09-27 07:11 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/dto/CarResponse.kt
> +    val isDeleted: Boolean?
fixed

2024-09-27 07:11 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/exceptionhandler/ExceptionHandler.kt
> +        return baseCustomException;
replaced with expression functions

2024-09-27 07:12 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/mapper/CarRequestToCar.kt
> +            source.isDeleted!!
fixed

2024-09-27 07:13 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/mapper/DriverRequestToDriver.kt
> +        car.id = source.carId
I'm sorry, but I don't understand why I need to use this function here.

2024-09-27 07:13 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/mapper/DriverRequestToDriver.kt
> +            source.isDeleted!!
fixed

2024-09-27 07:16 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/controller/DriverController.kt
> +        return ResponseEntity("Deleted successfully", HttpStatus.OK)
fixed

2024-09-27 07:16 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/controller/CarController.kt
> +@RequiredArgsConstructor
fixed

2024-09-27 07:25 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/dto/CarRequest.kt
> +)
As far as I understand, if you make fields not null, then when creating a DTO query object, if the field turns out to be null, a runtime exception related to assigning null will be thrown in Kotlin. But I need the validation exception to be thrown.

2024-09-30 06:48 UTC, psidarovich requested changes

2024-09-30 06:48 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/controller/CarController.kt
Well done. Liked your usage of ResponseStatus and no ResponseEntity objects

2024-09-30 06:48 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/dto/CarRequest.kt
> +)
Yes, you are right. But it's better to make fields non nullable and somehow catch the exception with returning 400 status

2024-10-05 13:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/mapper/DriverRequestToDriver.kt
> +        car.id = source.carId
Will tell you on daily meeting

2024-10-05 13:41 UTC, psidarovich approved these changes

2024-10-06 21:51 UTC, merged