Implemented inter-service requests
cooperative0zero/driver-service pull request #2
Opened 2024-10-08 00:04 UTC by cooperative0zero

Inter-service requests are configured and implemented. Retry mechanism is provided.

2024-10-12 07:41 UTC, psidarovich requested changes

2024-10-12 07:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/client/PassengerServiceClient.kt
> +    fun getById(@PathVariable("id") id: Long?): PassengerResponse
Why does id nullable?

2024-10-12 07:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/dto/PassengerResponse.kt
> +    val fmlNames: String,
Better to name fullName - it means that it will include first, middle and last names

2024-10-12 07:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/dto/RideResponse.kt
> +)
Make immutable - use data class

2024-10-12 07:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/dto/RideResponse.kt
> +)
And remove empty lines, there is no need in them

2024-10-12 07:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/kafka/consumer/RatingConsumer.kt
> +        println(driverEvent)
println()?

2024-10-12 07:41 UTC, psidarovich commented on src/main/kotlin/com/modsen/software/driver/kafka/consumer/RideConsumer.kt
> +        println(rideEvent)
same here

2024-10-25 17:00 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/client/PassengerServiceClient.kt
> +    fun getById(@PathVariable("id") id: Long?): PassengerResponse
fixed

2024-10-25 17:00 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/dto/PassengerResponse.kt
> +    val fmlNames: String,
fixed

2024-10-25 17:01 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/dto/RideResponse.kt
> +)
fixed

2024-10-25 17:03 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/kafka/consumer/RatingConsumer.kt
> +        println(driverEvent)
I used it for debugging purposes. In the future, there will be some business logic. Replaced it with a logger call.

2024-10-25 17:03 UTC, cooperative0zero commented on src/main/kotlin/com/modsen/software/driver/kafka/consumer/RideConsumer.kt
> +        println(rideEvent)
fixed

2024-10-27 14:37 UTC, psidarovich approved these changes

2024-10-28 00:07 UTC, merged